public class NewSampleClass {
    string name ='Sandeep';
    public integer price = 1000;
    public double change = 123.456;
    boolean isMale = true;
    
    public void myMethod1(){
        system.debug('This is First Method');
        system.debug(name);
        system.debug(price);
    }
    
    public void myMethod2(){
        system.debug('This is Second Method');
        system.debug(change);
        system.debug(isMale);
    }
    
    public void myMethod3(){
        system.debug('This is Third Method');
    }

        
}