public class SubClass extends SuperClass{ 
    public integer price;
    public string first= 'abc';
    public string las= 'xyz'; 
    public subclass(string first,string middle,string last,integer price){
        super(first,middle,last);
        //super.printName();
		//system.debug(price); 
  		//super.printFL();
		//super();
        //system.debug('My first name is :' +first+ 'and Last name is : ' +last+ 'and price :' +price);      
    }
    /*public SubClass(){
        super();
        super.printName();
        super.printFL();
    }
    
    
    
    public void printFLL(string z,integer x){
        super();
        system.debug('My first name is :' +z+ 'and Last name is : ' +last+ 'and price :' +price);      
    }*/
    
    
    
    
    
    
}